# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvQYhnhnGITEQU4PxfIBejKecrku_5qO
"""

def reverse_string(s):
  """Reverses the given string."""
  return s[::-1]

print(reverse_string("Hello, World!"))